apiVersion: v1
kind: Service
metadata:
  name: employee-management-system
spec:
  type: NodePort
  selector:
    app: employee-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007